name: http_downloader
description: "Simply download your files from the internet and save them to the desired location on your device."
version: 0.0.2

repository: https://github.com/hasan-bulut/http_downloader
issue_tracker: https://github.com/hasan-bulut/http_downloader/issues

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  
flutter: